# -*- coding: utf-8 -*-
"""Copia de Exercise_Bot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/189Ar3bi-22lPNGYn2J0mtzlwh7jpe44F
"""

#este es el que se esta usando, que esta automatizado la parte de la estrategia y crear el archivo csv

#!pip install git+https://github.com/Marmaresp/trading-bot-lw-latam.git -q

#!pip install git+https://github.com/Marmaresp/trading-bot-lw-latam.git@test -q # -> este será el nuevo que use para los cambios de la automatización

from cryptobot import CryptoBot
import requests

# 1. Crear bot (todos los parámetros tienen defaults)
bot = CryptoBot(symbol="SOL", timeframe="1h", exchange="binanceus",
                max_position_pct=0.10, stop_loss_pct=0.05, take_profit_pct=0.10) #Aquí se cambian los parametros como yo quiera

#import requests

symbols = [s['symbol'] for s in requests.get("https://api.binance.us/api/v3/exchangeInfo").json()['symbols']]
symbols

bot.fetch_data(last_n=500) #Aquí cambiarle para los parámetros de tiempo

# 2. Cargar datos
bot.summary()
bot.plot_price()



# 3. Crear features
#bot.create_features()
bot.create_features(mode="full") #igual aquí

# 4. Detectar régimen de mercado (GMM: Bull, Bear, Sideways)
bot.detect_regime()
bot.regime_report()

bot.recommend_strategies()

# 5. Elegir estrategia
bot.recommend_strategies()
print(bot.selected_strategy)
#bot.select_strategy("trend_following") #Aquí se cambia esto también -> como ya se automatizo ya no se necesita

print("selected_strategy antes de entrenar:", bot.selected_strategy)

bot.recommend_strategies()
print("selected_strategy:", bot.selected_strategy)

#if bot.selected_strategy is None:
#    bot.select_strategy("trend_following")

bot.train_models()

# 6. Entrenar modelos
bot.train_models()
bot.optimize_model()               # GridSearchCV con TimeSeriesSplit
bot.feature_importance()

#print(bot.feature_importances_)
bot.plot_feature_importance()

bot.data.columns

bot.data.head()

bot.data.tail()

bot.data[['Close']].head()

bot.data[['Close']].tail()

bot.summary()

# 7. Generar señales (1=BUY, -1=SELL, 0=HOLD)
bot.get_signals()
bot.plot_signals()

df_export = bot.data[["Open", "High", "Low", "Close"]].copy()


df_export = df_export.reset_index()

if bot.signals is not None:
    df_export["signals"] = bot.signals

df_export["model_name"] = bot.model_name

accuracy = None
if bot.model_metrics is not None:
    accuracy = (
        bot.model_metrics.get("accuracy")
        or bot.model_metrics.get("Accuracy")
        or bot.model_metrics.get("test_accuracy")
        or bot.model_metrics.get("oos_accuracy")
    )

df_export["accuracy"] = accuracy

df_export.to_csv("result_OHC.csv", index=False)

# 8. Backtesting
bot.backtest()
bot.backtest_plot()
bot.plot_performance()

#git add script.py